In [7]:
#copiar a /home/itt/anaconda2/bin el archivo
import pandas as pd
df = pd.read_csv('Bienestar.csv')

In [8]:
len(df)

10654

In [9]:
df

,anio_reg,trimestre,folio,hog_ent_1,hog_ent_2,id_pobla,sexo,edad,edo_conyug,grado_inst,...,upm_dis,estrato,factor,gct_per,tam_hog,gr_edad,n_inst,cond_act,gr_satis,gr_feliz
0,2012,1,191204070,1,0,1,1,59,6,4,...,5050,2,7570,8030.0000,3,3,1,1,4,3
1,2012,1,141201084,1,0,1,1,24,1,1,...,3760,2,8377,4803.6667,3,1,5,1,3,3
2,2012,1,311204053,1,0,2,2,61,6,2,...,8350,1,16455,3839.5000,7,4,1,1,4,4
3,2012,1,131206082,1,0,2,2,28,6,3,...,3480,3,4610,7395.0000,3,1,5,1,4,4
4,2012,1,261206013,1,0,1,1,38,6,4,...,6950,2,2314,10697.6667,3,2,6,1,3,4
5,2012,1,201203058,1,0,1,1,52,6,3,...,5350,3,10348,32195.9167,3,3,7,1,3,3
6,2012,1,31203033,3,0,1,1,20,5,3,...,870,1,3897,22481.0000,1,1,5,1,2,2
7,2012,1,91201092,1,0,2,2,37,1,3,...,2560,2,5459,16143.4167,3,2,4,4,3,2
8,2012,1,151201119,1,0,1,1,37,6,4,...,4150,2,6412,6363.3000,5,2,6,1,4,4
9,2012,1,221204051,1,0,1,1,39,6,3,...,5950,3,5268,4951.7500,5,2,4,1,3,3
10,2012,1,111203058,1,0,1,1,56,6,1,...,3020,3,3443,15229.4000,5,3,7,3,4,4
11,2012,1,91202043,1,0,1,2,52,5,6,...,2340,2,9827,4407.3125,4,3,2,1,2,4
12,2012,1,321204056,1,0,4,2,22,6,4,...,8550,2,8861,5150.2000,5,1,6,5,4,4
13,2012,1,231202069,1,0,1,1,37,6,3,...,6190,2,10019,8324.2500,5,2,4,1,4,4
14,2012,1,191203037,1,0,1,1,49,3,4,...,5210,4,2593,66322.0000,1,3,6,1,3,3
15,2012,1,161205061,1,0,1,1,50,1,5,...,4490,2,3200,16867.5000,5,3,6,1,3,4
16,2012,1,261201027,1,0,2,1,53,2,1,...,6940,2,2133,10739.5000,2,3,6,1,3,4
17,2012,1,131201045,1,0,2,2,41,6,3,...,3510,1,8561,2616.0000,5,2,4,4,2,2
18,2012,1,61205067,1,0,1,1,37,6,3,...,1560,2,5288,7931.0625,4,2,4,1,4,4
19,2012,1,281203004,1,0,1,1,32,6,2,...,7340,1,1614,39054.7500,3,2,7,1,4,4
20,2012,1,231203001,1,0,2,2,40,1,1,...,6100,4,4302,10540.0000,3,2,6,1,4,4
21,2012,1,161201004,1,0,1,2,69,4,0,...,4320,3,7793,10222.6500,5,4,0,4,4,4
22,2012,1,31202058,1,0,1,1,44,5,6,...,810,2,2881,14427.0000,1,2,2,1,3,1
23,2012,1,131201041,1,0,2,2,36,1,6,...,3510,1,8561,2189.1000,5,2,2,4,2,2
24,2012,1,271204066,1,0,1,1,59,6,5,...,7210,2,11696,4239.6429,7,3,1,1,3,4
25,2012,1,131201055,1,0,1,2,44,1,0,...,3510,1,4280,5964.5000,3,2,0,1,2,3
26,2012,1,311204047,1,0,2,2,39,1,4,...,8350,1,9977,2142.7500,6,2,1,4,4,4
27,2012,1,201202049,1,0,1,1,63,6,0,...,5460,1,9353,2512.6250,4,4,0,1,3,3
28,2012,1,81204051,1,0,2,2,26,6,3,...,2150,2,3714,2606.0417,6,1,4,1,3,4
29,2012,1,31205052,1,0,1,1,31,6,3,...,820,1,3257,6441.5000,4,2,4,1,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10624,2012,1,321206001,1,0,1,1,32,6,3,...,8470,3,6170,22278.8125,4,2,5,1,4,4
10625,2012,1,321206002,1,0,1,2,62,3,3,...,8470,3,5683,6225.3333,3,4,2,3,2,2
10626,2012,1,321206006,1,0,4,2,53,5,6,...,8470,3,10442,2138.7500,4,3,2,4,4,4
10627,2012,1,321206009,1,0,3,1,38,5,3,...,8470,3,15425,3472.1000,5,2,4,1,4,3
10628,2012,1,321206011,1,0,3,2,53,5,3,...,8470,3,15664,3797.7500,6,3,4,4,4,4
10629,2012,1,321206012,1,0,2,1,26,6,3,...,8470,3,6425,7285.5000,3,1,4,1,4,4
10630,2012,1,321206014,1,0,1,1,56,6,5,...,8470,3,8532,34819.0000,3,3,6,1,4,4
10631,2012,1,321206016,1,0,2,1,28,6,6,...,8520,2,4474,6954.3750,2,1,2,1,4,4
10632,2012,1,321206019,1,0,2,2,34,6,5,...,8520,2,3599,15615.8333,6,2,6,1,3,3
10633,2012,1,321206021,1,0,2,2,36,6,3,...,8520,2,3599,4521.9167,6,2,4,1,1,1
10634,2012,1,321206022,1,0,1,1,60,6,5,...,8520,2,4256,12519.5000,3,4,6,1,3,4
10635,2012,1,321206023,1,0,1,2,65,4,3,...,8520,2,1979,17855.2500,1,4,4,1,3,3
10636,2012,1,321206024,1,0,2,2,69,6,3,...,8520,2,5937,7731.6667,3,4,4,4,4,3
10637,2012,1,321206028,1,0,2,2,34,6,3,...,8520,2,3599,6576.0000,4,2,4,1,2,3
10638,2012,1,321206030,1,0,1,1,50,6,2,...,8520,2,3961,10207.1000,5,3,6,1,3,2
10639,2012,1,321206031,1,0,2,2,60,4,2,...,8520,2,1979,16082.0000,2,4,1,4,4,4
10640,2012,1,321206033,1,0,2,2,36,6,3,...,8520,2,3599,6517.3125,4,2,4,4,2,3
10641,2012,1,321206035,1,0,4,1,23,5,3,...,8520,2,8948,9240.3750,4,1,4,2,4,4
10642,2012,1,321206037,1,0,3,1,42,5,3,...,8520,2,6445,11158.0625,4,2,5,1,2,1
10643,2012,1,321206038,1,0,1,2,51,2,6,...,8520,2,1818,4517.7500,2,3,2,1,4,4
10644,2012,1,321206039,1,0,1,1,59,6,5,...,8520,2,9903,2663.7500,6,3,1,1,4,4
10645,2012,1,321206040,1,0,2,2,26,6,6,...,8520,2,4075,4044.6667,3,1,2,4,4,4
10646,2012,1,321206043,1,0,4,1,20,5,2,...,8520,2,8948,3333.8500,5,1,3,1,2,3
10647,2012,1,321206044,1,0,2,2,27,6,3,...,8520,2,4075,8415.5000,3,1,4,4,3,3
10648,2012,1,321206048,1,0,2,2,32,6,3,...,8390,2,4931,8616.0500,5,2,5,1,3,3
10649,2012,1,321206050,1,0,2,2,32,6,6,...,8390,2,4931,3700.8333,3,2,2,4,3,3
10650,2012,1,321206052,1,0,1,1,40,6,3,...,8390,2,8830,6044.6500,5,2,1,1,4,4
10651,2012,1,321206053,1,0,2,2,44,6,3,...,8390,2,4931,23187.3333,3,2,4,1,1,3
10652,2012,1,321206058,1,0,2,2,56,6,3,...,8390,2,4981,31808.7500,2,3,4,1,4,4
10653,2012,1,321206059,1,0,1,1,32,6,3,...,8390,2,5887,6632.7500,4,2,4,1,3,4

In [21]:
df.to_cvs("misalida2.cvs", index=False) #Exportar

AttributeError: 'DataFrame' object has no attribute 'to_cvs'